In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
df=pd.read_csv('/content/drive/My Drive/Colab Notebooks/mnist.csv')

In [5]:

df.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8    ...     pixel774  pixel775  pixel776  pixel777  pixel778  \
0       0    ...            0         0         0         0         0   
1       0    ...            0         0         0         0         0   
2       0    ...            0         0         0         0         0   
3       0    ...            0         0         0         0         0   
4       0    ...            0         0         0         0         0   

   pixel779  pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0         0  
1         0         0         0         0         0  
2         0         0         0         0         0  
3         0         0         0         0         0  
4         0         0         0         0         0  

[5 rows x 785 columns]

In [0]:
x=df.iloc[:,1:]

In [0]:
y=df.iloc[:,0:1]

In [0]:

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [9]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/data.py:625: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
/usr/local/lib/python3.6/dist-packages/sklearn/base.py:462: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  after removing the cwd from sys.path.


In [0]:
from sklearn.decomposition import PCA
pca=PCA(0.95)
x_train=pca.fit_transform(x_train)
x_test=pca.transform(x_test)

# **Linear Kernel**

In [11]:
from sklearn.svm import SVC
classifier=SVC(kernel='linear',random_state=0)
classifier.fit(x_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=0,
  shrinking=True, tol=0.001, verbose=False)

In [0]:
y_pred=classifier.predict(x_test).reshape(8400,1)

In [22]:
result=pd.DataFrame({'Actual':[y_test.values],'Predicted':[y_pred]})
result.head()

Actual  \
0  [[3], [6], [9], [5], [6], [5], [6], [0], [0], ...   

                                           Predicted  
0  [[3], [6], [9], [5], [6], [0], [6], [0], [0], ...

In [23]:
from sklearn.metrics import confusion_matrix
matrix=confusion_matrix(y_test,y_pred)
matrix

array([[779,   0,   9,   2,   1,   7,   8,   0,   6,   1],
       [  0, 948,   5,   2,   1,   1,   1,   1,   1,   1],
       [  6,  11, 797,   8,   8,   2,   7,   8,  10,   3],
       [  2,   2,  26, 787,   2,  19,   0,   6,  14,   5],
       [  3,   7,  11,   1, 768,   3,   5,   7,   2,  20],
       [ 11,   3,   6,  19,   4, 684,  10,   2,  12,   5],
       [  7,   1,  11,   0,   8,   8, 804,   0,   2,   0],
       [  1,   3,  14,   5,  10,   1,   1, 844,   4,  16],
       [  4,  11,   5,  23,   3,  23,   9,   1, 685,   4],
       [  9,   5,   9,   8,  18,   5,   0,  23,   7, 728]])

In [24]:
from sklearn.metrics import classification_report
report=classification_report(y_test,y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.95      0.96      0.95       813
           1       0.96      0.99      0.97       961
           2       0.89      0.93      0.91       860
           3       0.92      0.91      0.92       863
           4       0.93      0.93      0.93       827
           5       0.91      0.90      0.91       756
           6       0.95      0.96      0.95       841
           7       0.95      0.94      0.94       899
           8       0.92      0.89      0.91       768
           9       0.93      0.90      0.91       812

   micro avg       0.93      0.93      0.93      8400
   macro avg       0.93      0.93      0.93      8400
weighted avg       0.93      0.93      0.93      8400



# **Poly Kernel**

In [25]:
classifier2=SVC(kernel='poly',random_state=0)
classifier2.fit(x_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='poly', max_iter=-1, probability=False, random_state=0,
  shrinking=True, tol=0.001, verbose=False)

In [0]:
y_pred=classifier2.predict(x_test).reshape(8400,1)

In [28]:
result=pd.DataFrame({'Actual':list(y_test.values),'Predicted':list(y_pred)})
result.head()

Actual Predicted
0    [3]       [3]
1    [6]       [6]
2    [9]       [9]
3    [5]       [5]
4    [6]       [6]

In [29]:
from sklearn.metrics import confusion_matrix
matrix=confusion_matrix(y_test,y_pred)
matrix

array([[796,   0,   2,   1,   2,   1,   5,   0,   5,   1],
       [  0, 950,   3,   2,   1,   1,   1,   1,   2,   0],
       [  3,   0, 837,   4,   2,   0,   1,   2,  10,   1],
       [  2,   0,   6, 825,   1,  11,   0,   4,  11,   3],
       [  1,   2,   4,   0, 803,   2,   2,   0,   2,  11],
       [  0,   0,   1,   5,   1, 741,   4,   0,   4,   0],
       [  1,   0,   0,   0,   1,   6, 832,   0,   1,   0],
       [  1,   2,   5,   1,   6,   1,   0, 872,   2,   9],
       [  2,   2,   1,   2,   1,   6,   1,   2, 750,   1],
       [  3,   1,   3,   2,   8,   4,   0,  11,   5, 775]])

In [30]:
from sklearn.metrics import classification_report
report=classification_report(y_test,y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.98      0.98      0.98       813
           1       0.99      0.99      0.99       961
           2       0.97      0.97      0.97       860
           3       0.98      0.96      0.97       863
           4       0.97      0.97      0.97       827
           5       0.96      0.98      0.97       756
           6       0.98      0.99      0.99       841
           7       0.98      0.97      0.97       899
           8       0.95      0.98      0.96       768
           9       0.97      0.95      0.96       812

   micro avg       0.97      0.97      0.97      8400
   macro avg       0.97      0.97      0.97      8400
weighted avg       0.97      0.97      0.97      8400



# **Sigmoid Kernel**

In [31]:
classifier4=SVC(kernel='sigmoid',random_state=0)
classifier4.fit(x_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='sigmoid', max_iter=-1, probability=False, random_state=0,
  shrinking=True, tol=0.001, verbose=False)

In [0]:
y_pred=classifier4.predict(x_test).reshape(8400,1)

In [34]:
result=pd.DataFrame({'Actual':list(y_test.values),'Predicted':list(y_pred)})
result.head()

Actual Predicted
0    [3]       [0]
1    [6]       [6]
2    [9]       [9]
3    [5]       [5]
4    [6]       [6]

In [35]:
from sklearn.metrics import confusion_matrix
matrix=confusion_matrix(y_test,y_pred)
matrix

array([[679,   0,  33,  11,   2,  45,  29,   1,   9,   4],
       [  0, 919,  16,   7,   1,   1,   1,   3,  11,   2],
       [ 47,  25, 631,  35,  13,   9,  61,   7,  25,   7],
       [ 27,  12,  47, 662,   3,  66,  11,  15,   9,  11],
       [ 19,  10,  16,   6, 663,   5,  21,  19,   2,  66],
       [ 66,  22,   7,  67,   6, 541,   2,   4,  32,   9],
       [ 72,   3,  56,   2,   7,  16, 676,   0,   9,   0],
       [ 28,   9,  25,  28,  14,   2,   3, 729,   0,  61],
       [ 35,  40,  12,  39,   7,  68,   6,   5, 541,  15],
       [ 24,   2,  16,  11,  59,  10,   1,  69,   9, 611]])

In [36]:
from sklearn.metrics import classification_report
report=classification_report(y_test,y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.68      0.84      0.75       813
           1       0.88      0.96      0.92       961
           2       0.73      0.73      0.73       860
           3       0.76      0.77      0.76       863
           4       0.86      0.80      0.83       827
           5       0.71      0.72      0.71       756
           6       0.83      0.80      0.82       841
           7       0.86      0.81      0.83       899
           8       0.84      0.70      0.76       768
           9       0.78      0.75      0.76       812

   micro avg       0.79      0.79      0.79      8400
   macro avg       0.79      0.79      0.79      8400
weighted avg       0.80      0.79      0.79      8400

